export type EventParticipation = {
  candidateId: string
  candidateName: string
  battalion: string
  position: number
  performanceTime: string
  status: "Completed" | "Disqualified"
  rank: string
  state: string
  unitRole: string
  performanceNote: string
}

export type EventRecord = {
  id: string
  title: string
  category: string
  date: string
  startTime: string
  location: string
  description: string
  participants: EventParticipation[]
}

export type AwardWinner = {
  candidateId: string
  candidateName: string
  battalion: string
  awardedOn: string
  awardedBy: string
  citation: string
  relatedEventId?: string
}

export type AwardRecord = {
  id: string
  title: string
  category: string
  description: string
  winners: AwardWinner[]
}

export type CandidateProfile = {
  candidateId: string
  candidateName: string
  rank: string
  battalion: string
  state: string
  joinedOn: string
  specialization: string
}

export const CANDIDATE_PROFILES: CandidateProfile[] = [
  {
    candidateId: "AGN-2024-0103",
    candidateName: "Arjun Mehra",
    rank: "Lance Naik",
    battalion: "RR-1",
    state: "Punjab",
    joinedOn: "2024-01-15",
    specialization: "Obstacle endurance, combat leadership",
  },
  {
    candidateId: "AGN-2024-0201",
    candidateName: "Vikram Nair",
    rank: "Sepoy",
    battalion: "PARA-2",
    state: "Kerala",
    joinedOn: "2024-02-01",
    specialization: "Combat drills, tactical movement",
  },
  {
    candidateId: "AGN-2024-0304",
    candidateName: "Ranjit Singh",
    rank: "Lance Naik",
    battalion: "BEN-3",
    state: "Punjab",
    joinedOn: "2024-02-15",
    specialization: "Precision shooting",
  },
  {
    candidateId: "AGN-2024-0402",
    candidateName: "Vijay Deshmukh",
    rank: "Sepoy",
    battalion: "MAR-4",
    state: "Maharashtra",
    joinedOn: "2024-03-01",
    specialization: "All-round field drills",
  },
  {
    candidateId: "AGN-2024-0106",
    candidateName: "Mahesh Choudhary",
    rank: "Sepoy",
    battalion: "RR-1",
    state: "Rajasthan",
    joinedOn: "2024-01-15",
    specialization: "Weapons handling",
  },
  {
    candidateId: "AGN-2024-0204",
    candidateName: "Deepak Yadav",
    rank: "Sepoy",
    battalion: "PARA-2",
    state: "Bihar",
    joinedOn: "2024-02-01",
    specialization: "Rapid response drills",
  },
  {
    candidateId: "AGN-2024-0401",
    candidateName: "Suresh Patil",
    rank: "Sepoy",
    battalion: "MAR-4",
    state: "Maharashtra",
    joinedOn: "2024-03-01",
    specialization: "Field mobility",
  },
  {
    candidateId: "AGN-2024-0101",
    candidateName: "Rajveer Singh Chauhan",
    rank: "Sepoy",
    battalion: "RR-1",
    state: "Rajasthan",
    joinedOn: "2024-01-15",
    specialization: "Combat simulation",
  },
  {
    candidateId: "AGN-2024-0301",
    candidateName: "Sourav Das",
    rank: "Sepoy",
    battalion: "BEN-3",
    state: "West Bengal",
    joinedOn: "2024-02-15",
    specialization: "Team tactical coordination",
  },
  {
    candidateId: "AGN-2024-0404",
    candidateName: "Vijay Deshmukh",
    rank: "Sepoy",
    battalion: "MAR-4",
    state: "Maharashtra",
    joinedOn: "2024-03-01",
    specialization: "Field execution",
  },
]

export const EVENT_RECORDS: EventRecord[] = [
  {
    id: "national-obstacle-trial-2025",
    title: "National Obstacle Trial 2025",
    category: "Physical",
    date: "2025-03-10",
    startTime: "08:30 IST",
    location: "Jaipur Training Ground",
    description:
      "Obstacle endurance and speed challenge for all battalion qualifiers.",
    participants: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        position: 1,
        performanceTime: "03:18",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Lead runner",
        performanceNote: "Clean run, no obstacle penalties.",
      },
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 2,
        performanceTime: "03:26",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Sprint specialist",
        performanceNote: "Strong final segment recovery.",
      },
      {
        candidateId: "AGN-2024-0304",
        candidateName: "Ranjit Singh",
        battalion: "BEN-3",
        position: 3,
        performanceTime: "03:34",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Obstacle specialist",
        performanceNote: "One rope-climb retry, otherwise stable.",
      },
      {
        candidateId: "AGN-2024-0402",
        candidateName: "Vijay Deshmukh",
        battalion: "MAR-4",
        position: 4,
        performanceTime: "03:41",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Reserve competitor",
        performanceNote: "Consistent pace throughout course.",
      },
    ],
  },
  {
    id: "precision-shooting-cup-2025",
    title: "Precision Shooting Cup 2025",
    category: "Weapons",
    date: "2025-05-18",
    startTime: "10:00 IST",
    location: "Central Marksmanship Range, Agra",
    description:
      "Long-range and rapid fire accuracy assessment across battalions.",
    participants: [
      {
        candidateId: "AGN-2024-0304",
        candidateName: "Ranjit Singh",
        battalion: "BEN-3",
        position: 1,
        performanceTime: "98/100",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Primary marksman",
        performanceNote: "Highest accuracy in long-range segment.",
      },
      {
        candidateId: "AGN-2024-0106",
        candidateName: "Mahesh Choudhary",
        battalion: "RR-1",
        position: 2,
        performanceTime: "95/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Rapid-fire specialist",
        performanceNote: "Best rapid-fire grouping.",
      },
      {
        candidateId: "AGN-2024-0204",
        candidateName: "Deepak Yadav",
        battalion: "PARA-2",
        position: 3,
        performanceTime: "93/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Bihar",
        unitRole: "Range qualifier",
        performanceNote: "Clean execution in timed lane.",
      },
      {
        candidateId: "AGN-2024-0401",
        candidateName: "Suresh Patil",
        battalion: "MAR-4",
        position: 4,
        performanceTime: "89/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Support marksman",
        performanceNote: "Stable control, missed two long shots.",
      },
    ],
  },
  {
    id: "combat-drill-finals-2025",
    title: "Combat Drill Finals 2025",
    category: "Combat",
    date: "2025-08-02",
    startTime: "15:00 IST",
    location: "Field Simulation Arena, Pune",
    description:
      "Section-level tactical drill final judged on response time and execution.",
    participants: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 1,
        performanceTime: "12:42",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Team lead",
        performanceNote: "Fastest tactical decision cycle.",
      },
      {
        candidateId: "AGN-2024-0101",
        candidateName: "Rajveer Singh Chauhan",
        battalion: "RR-1",
        position: 2,
        performanceTime: "12:58",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Forward scout",
        performanceNote: "Strong objective control under pressure.",
      },
      {
        candidateId: "AGN-2024-0301",
        candidateName: "Sourav Das",
        battalion: "BEN-3",
        position: 3,
        performanceTime: "13:09",
        status: "Completed",
        rank: "Sepoy",
        state: "West Bengal",
        unitRole: "Communications support",
        performanceNote: "Good coordination and timing discipline.",
      },
      {
        candidateId: "AGN-2024-0404",
        candidateName: "Vijay Deshmukh",
        battalion: "MAR-4",
        position: 4,
        performanceTime: "13:20",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Rear guard",
        performanceNote: "Balanced performance in all checkpoints.",
      },
    ],
  },
  {
    id: "batch-rally-200m-2024",
    title: "Batch Rally 200m Sprint 2024",
    category: "Physical",
    date: "2024-11-20",
    startTime: "09:00 IST",
    location: "Jaipur Military Ground",
    description: "Annual inter-battalion 200m sprint competition for the new batch.",
    participants: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        position: 1,
        performanceTime: "22.4s",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Sprinter",
        performanceNote: "Winner - Fastest time in batch.",
      },
      {
        candidateId: "AGN-2024-0101",
        candidateName: "Rajveer Singh Chauhan",
        battalion: "RR-1",
        position: 2,
        performanceTime: "23.1s",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Sprinter",
        performanceNote: "Second place - Strong finish.",
      },
      {
        candidateId: "AGN-2024-0401",
        candidateName: "Suresh Patil",
        battalion: "MAR-4",
        position: 3,
        performanceTime: "23.5s",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Sprinter",
        performanceNote: "Third place - Consistent pace.",
      },
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 4,
        performanceTime: "23.8s",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Sprinter",
        performanceNote: "Good start, maintained speed.",
      },
      {
        candidateId: "AGN-2024-0301",
        candidateName: "Sourav Das",
        battalion: "BEN-3",
        position: 5,
        performanceTime: "24.2s",
        status: "Completed",
        rank: "Sepoy",
        state: "West Bengal",
        unitRole: "Sprinter",
        performanceNote: "Steady performance.",
      },
    ],
  },
  {
    id: "mental-resilience-challenge-2024",
    title: "Mental Resilience Challenge 2024",
    category: "Mental",
    date: "2024-12-15",
    startTime: "10:00 IST",
    location: "Psychological Training Center, Delhi",
    description: "Assessment of mental toughness, stress management, and decision making under pressure.",
    participants: [
      {
        candidateId: "AGN-2024-0102",
        candidateName: "Naman Sharma",
        battalion: "RR-1",
        position: 1,
        performanceTime: "98/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Mental endurance candidate",
        performanceNote: "Top score in stress simulation.",
      },
      {
        candidateId: "AGN-2024-0402",
        candidateName: "Rohini Jadhav",
        battalion: "MAR-4",
        position: 2,
        performanceTime: "95/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Mental endurance candidate",
        performanceNote: "Excellent composure throughout.",
      },
      {
        candidateId: "AGN-2024-0202",
        candidateName: "Ananya Krishnan",
        battalion: "PARA-2",
        position: 3,
        performanceTime: "92/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Tamil Nadu",
        unitRole: "Mental endurance candidate",
        performanceNote: "Strong decision making.",
      },
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        position: 4,
        performanceTime: "90/100",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Mental endurance candidate",
        performanceNote: "Good recovery from stress test.",
      },
    ],
  },
  {
    id: "academic-excellence-2024",
    title: "Academic Excellence Award 2024",
    category: "Academic",
    date: "2024-12-28",
    startTime: "11:00 IST",
    location: "Army Education Corps Center",
    description: "Written examination covering military tactics, strategy, and technical knowledge.",
    participants: [
      {
        candidateId: "AGN-2024-0102",
        candidateName: "Naman Sharma",
        battalion: "RR-1",
        position: 1,
        performanceTime: "96/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Academic candidate",
        performanceNote: "Highest written score.",
      },
      {
        candidateId: "AGN-2024-0302",
        candidateName: "Rekha Bose",
        battalion: "BEN-3",
        position: 2,
        performanceTime: "94/100",
        status: "Completed",
        rank: "Sepoy",
        state: "West Bengal",
        unitRole: "Academic candidate",
        performanceNote: "Second highest score.",
      },
      {
        candidateId: "AGN-2024-0202",
        candidateName: "Ananya Krishnan",
        battalion: "PARA-2",
        position: 3,
        performanceTime: "91/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Tamil Nadu",
        unitRole: "Academic candidate",
        performanceNote: "Strong theoretical knowledge.",
      },
    ],
  },
  {
    id: "battalion-physical-champion-2024",
    title: "Battalion Physical Championship 2024",
    category: "Physical",
    date: "2024-10-05",
    startTime: "06:00 IST",
    location: "All Battalion Grounds",
    description: "Multi-event physical competition across all battalions.",
    participants: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        position: 1,
        performanceTime: "Aggregate 95",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "All-rounder",
        performanceNote: "Champion - Best aggregate score.",
      },
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 2,
        performanceTime: "Aggregate 92",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "All-rounder",
        performanceNote: "Runner-up - Strong overall performance.",
      },
      {
        candidateId: "AGN-2024-0401",
        candidateName: "Suresh Patil",
        battalion: "MAR-4",
        position: 3,
        performanceTime: "Aggregate 88",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "All-rounder",
        performanceNote: "Third place.",
      },
    ],
  },
  {
    id: "all-india-ranking-2025",
    title: "All India Agniveer Ranking 2025",
    category: "Overall",
    date: "2025-03-15",
    startTime: "09:00 IST",
    location: "PAN India",
    description: "National-level ranking based on的综合 performance across all parameters.",
    participants: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        position: 1,
        performanceTime: "Rank #1",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Top performer",
        performanceNote: "All India First Rank.",
      },
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 2,
        performanceTime: "Rank #3",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Top performer",
        performanceNote: "All India Top 5.",
      },
      {
        candidateId: "AGN-2024-0304",
        candidateName: "Ranjit Singh",
        battalion: "BEN-3",
        position: 3,
        performanceTime: "Rank #5",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Top performer",
        performanceNote: "All India Top 10.",
      },
    ],
  },
  {
    id: "best-female-recruit-2024",
    title: "Best Female Recruit Batch 2024",
    category: "Special",
    date: "2024-12-01",
    startTime: "10:00 IST",
    location: "Regional Command HQ",
    description: "Recognition for best performing female recruit in the batch.",
    participants: [
      {
        candidateId: "AGN-2024-0105",
        candidateName: "Dharmesh Rajput",
        battalion: "RR-1",
        position: 1,
        performanceTime: "Score 88",
        status: "Completed",
        rank: "Sepoy",
        state: "UP",
        unitRole: "Best female recruit",
        performanceNote: "Winner - Outstanding overall performance.",
      },
      {
        candidateId: "AGN-2024-0402",
        candidateName: "Rohini Jadhav",
        battalion: "MAR-4",
        position: 2,
        performanceTime: "Score 85",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Female recruit",
        performanceNote: "Second place.",
      },
    ],
  },
  {
    id: "best-shooter-jan-2025",
    title: "Best Shooter January 2025",
    category: "Weapons",
    date: "2025-01-20",
    startTime: "08:00 IST",
    location: "Central Shooting Range",
    description: "Monthly weapons qualification and accuracy assessment.",
    participants: [
      {
        candidateId: "AGN-2024-0106",
        candidateName: "Mahesh Choudhary",
        battalion: "RR-1",
        position: 1,
        performanceTime: "97/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Rajasthan",
        unitRole: "Primary marksman",
        performanceNote: "Highest monthly score.",
      },
      {
        candidateId: "AGN-2024-0304",
        candidateName: "Ranjit Singh",
        battalion: "BEN-3",
        position: 2,
        performanceTime: "95/100",
        status: "Completed",
        rank: "Lance Naik",
        state: "Punjab",
        unitRole: "Marksman",
        performanceNote: "Second place.",
      },
    ],
  },
  {
    id: "para-jump-certification-2024",
    title: "Para Jump Certification March 2024",
    category: "Special Operations",
    date: "2024-03-15",
    startTime: "05:00 IST",
    location: "Arasar Movement Training Center",
    description: "Mandatory para jumping certification for airborne candidates.",
    participants: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 1,
        performanceTime: "5 jumps",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Para trooper",
        performanceNote: "Certified - All jumps successful.",
      },
      {
        candidateId: "AGN-2024-0204",
        candidateName: "Deepak Yadav",
        battalion: "PARA-2",
        position: 2,
        performanceTime: "5 jumps",
        status: "Completed",
        rank: "Sepoy",
        state: "Bihar",
        unitRole: "Para trooper",
        performanceNote: "Certified - All jumps successful.",
      },
    ],
  },
  {
    id: "best-para-recruit-2024",
    title: "Best Para Recruit 2024",
    category: "Special Operations",
    date: "2024-04-01",
    startTime: "09:00 IST",
    location: "Para Training School",
    description: "Competition among para recruits for best overall performance.",
    participants: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        position: 1,
        performanceTime: "Best Overall",
        status: "Completed",
        rank: "Sepoy",
        state: "Kerala",
        unitRole: "Best para recruit",
        performanceNote: "Winner - Highest aggregate in training.",
      },
    ],
  },
  {
    id: "top-academic-score-2024",
    title: "Top Academic Score 2024",
    category: "Academic",
    date: "2024-11-15",
    startTime: "10:00 IST",
    location: "Education Center",
    description: "Academic excellence in military studies.",
    participants: [
      {
        candidateId: "AGN-2024-0202",
        candidateName: "Ananya Krishnan",
        battalion: "PARA-2",
        position: 1,
        performanceTime: "98/100",
        status: "Completed",
        rank: "Sepoy",
        state: "Tamil Nadu",
        unitRole: "Academic topper",
        performanceNote: "Highest academic score.",
      },
    ],
  },
  {
    id: "best-combat-drill-2025",
    title: "Best Combat Drill March 2025",
    category: "Combat",
    date: "2025-03-20",
    startTime: "14:00 IST",
    location: "Combat Training Zone",
    description: "Individual combat drill competition.",
    participants: [
      {
        candidateId: "AGN-2024-0301",
        candidateName: "Sourav Das",
        battalion: "BEN-3",
        position: 1,
        performanceTime: "Best Drill",
        status: "Completed",
        rank: "Sepoy",
        state: "West Bengal",
        unitRole: "Combat specialist",
        performanceNote: "Winner - Best tactical execution.",
      },
    ],
  },
  {
    id: "sprint-champion-2024",
    title: "Sprint Champion 2024",
    category: "Physical",
    date: "2024-09-10",
    startTime: "07:00 IST",
    location: "Athletics Track",
    description: "100m and 200m sprint championship.",
    participants: [
      {
        candidateId: "AGN-2024-0401",
        candidateName: "Suresh Patil",
        battalion: "MAR-4",
        position: 1,
        performanceTime: "11.2s (100m)",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Sprint champion",
        performanceNote: "Winner - Fastest sprinter.",
      },
    ],
  },
  {
    id: "best-mental-resilience-2024",
    title: "Best Mental Resilience 2024",
    category: "Mental",
    date: "2024-12-20",
    startTime: "10:00 IST",
    location: "Psychological Center",
    description: "Annual mental toughness assessment.",
    participants: [
      {
        candidateId: "AGN-2024-0402",
        candidateName: "Rohini Jadhav",
        battalion: "MAR-4",
        position: 1,
        performanceTime: "Score 96",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Mental resilience topper",
        performanceNote: "Winner - Highest mental resilience score.",
      },
    ],
  },
  {
    id: "best-all-rounder-2024",
    title: "Best All-Rounder 2024",
    category: "Overall",
    date: "2024-12-31",
    startTime: "11:00 IST",
    location: "Command HQ",
    description: "Best overall performer across all categories.",
    participants: [
      {
        candidateId: "AGN-2024-0404",
        candidateName: "Vijay Deshmukh",
        battalion: "MAR-4",
        position: 1,
        performanceTime: "Aggregate 92",
        status: "Completed",
        rank: "Sepoy",
        state: "Maharashtra",
        unitRole: "Best all-rounder",
        performanceNote: "Winner - Highest aggregate score.",
      },
    ],
  },
]

export const AWARD_RECORDS: AwardRecord[] = [
  {
    id: "best-obstacle-runner",
    title: "Best Obstacle Runner",
    category: "Physical Excellence",
    description:
      "Given to the fastest candidate in obstacle endurance trials.",
    winners: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        awardedOn: "2025-03-10",
        awardedBy: "Brig. N. Kulkarni",
        citation: "Fastest course completion with zero penalties.",
        relatedEventId: "national-obstacle-trial-2025",
      },
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        awardedOn: "2024-12-14",
        awardedBy: "Maj. Ankit Verma",
        citation: "Best obstacle score in winter command meet.",
      },
    ],
  },
  {
    id: "marksman-of-the-quarter",
    title: "Marksman of the Quarter",
    category: "Weapons Mastery",
    description:
      "Awarded for highest aggregate shooting accuracy in the quarter.",
    winners: [
      {
        candidateId: "AGN-2024-0304",
        candidateName: "Ranjit Singh",
        battalion: "BEN-3",
        awardedOn: "2025-05-18",
        awardedBy: "Col. S. Rathore",
        citation: "Top score in precision and rapid fire segments.",
        relatedEventId: "precision-shooting-cup-2025",
      },
      {
        candidateId: "AGN-2024-0106",
        candidateName: "Mahesh Choudhary",
        battalion: "RR-1",
        awardedOn: "2025-02-01",
        awardedBy: "Maj. Ankit Verma",
        citation: "Consistent top-3 shooting performance all quarter.",
      },
    ],
  },
  {
    id: "battle-readiness-star",
    title: "Battle Readiness Star",
    category: "Combat Leadership",
    description:
      "Recognizes exceptional composure and tactical execution in combat drills.",
    winners: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        awardedOn: "2025-08-02",
        awardedBy: "Lt. Gen. P. Rawat",
        citation: "Highest tactical efficiency rating in finals.",
        relatedEventId: "combat-drill-finals-2025",
      },
      {
        candidateId: "AGN-2024-0101",
        candidateName: "Rajveer Singh Chauhan",
        battalion: "RR-1",
        awardedOn: "2025-08-02",
        awardedBy: "Lt. Gen. P. Rawat",
        citation: "Second highest tactical score with strong team command.",
        relatedEventId: "combat-drill-finals-2025",
      },
    ],
  },
  {
    id: "sprint-champion-award",
    title: "Sprint Champion Award",
    category: "Physical Excellence",
    description: "Given to the fastest sprinter in the annual athletics competition.",
    winners: [
      {
        candidateId: "AGN-2024-0401",
        candidateName: "Suresh Patil",
        battalion: "MAR-4",
        awardedOn: "2024-09-10",
        awardedBy: "Col. M. Shah",
        citation: "Fastest 100m and 200m sprinter in the competition.",
        relatedEventId: "sprint-champion-2024",
      },
    ],
  },
  {
    id: "mental-resilience-star",
    title: "Mental Resilience Star",
    category: "Mental Excellence",
    description: "Awarded for exceptional mental toughness and stress management.",
    winners: [
      {
        candidateId: "AGN-2024-0102",
        candidateName: "Naman Sharma",
        battalion: "RR-1",
        awardedOn: "2024-12-15",
        awardedBy: "Maj. R. Kapoor",
        citation: "Highest score in mental resilience challenge.",
        relatedEventId: "mental-resilience-challenge-2024",
      },
      {
        candidateId: "AGN-2024-0402",
        candidateName: "Rohini Jadhav",
        battalion: "MAR-4",
        awardedOn: "2024-12-20",
        awardedBy: "Maj. R. Kapoor",
        citation: "Best mental resilience in annual assessment.",
        relatedEventId: "best-mental-resilience-2024",
      },
    ],
  },
  {
    id: "academic-excellence-medal",
    title: "Academic Excellence Medal",
    category: "Academic",
    description: "Awarded for outstanding academic performance in military studies.",
    winners: [
      {
        candidateId: "AGN-2024-0102",
        candidateName: "Naman Sharma",
        battalion: "RR-1",
        awardedOn: "2024-12-28",
        awardedBy: "Brig. Academic Corps",
        citation: "Highest academic score in the batch.",
        relatedEventId: "academic-excellence-2024",
      },
      {
        candidateId: "AGN-2024-0302",
        candidateName: "Rekha Bose",
        battalion: "BEN-3",
        awardedOn: "2024-12-28",
        awardedBy: "Brig. Academic Corps",
        citation: "Second highest academic score.",
        relatedEventId: "academic-excellence-2024",
      },
      {
        candidateId: "AGN-2024-0202",
        candidateName: "Ananya Krishnan",
        battalion: "PARA-2",
        awardedOn: "2024-11-15",
        awardedBy: "Col. Education",
        citation: "Top academic score in para battalion.",
        relatedEventId: "top-academic-score-2024",
      },
    ],
  },
  {
    id: "best-female-recruit-award",
    title: "Best Female Recruit",
    category: "Special Recognition",
    description: "Recognizes best performing female recruit in the batch.",
    winners: [
      {
        candidateId: "AGN-2024-0105",
        candidateName: "Dharmesh Rajput",
        battalion: "RR-1",
        awardedOn: "2024-12-01",
        awardedBy: "Col. Women Cell",
        citation: "Outstanding overall performance among female recruits.",
        relatedEventId: "best-female-recruit-2024",
      },
    ],
  },
  {
    id: "best-combat-drill-award",
    title: "Best Combat Drill",
    category: "Combat Excellence",
    description: "Awarded for best tactical execution in combat drills.",
    winners: [
      {
        candidateId: "AGN-2024-0301",
        candidateName: "Sourav Das",
        battalion: "BEN-3",
        awardedOn: "2025-03-20",
        awardedBy: "Lt. Col. Combat",
        citation: "Best tactical execution and combat drill performance.",
        relatedEventId: "best-combat-drill-2025",
      },
    ],
  },
  {
    id: "all-rounder-star",
    title: "All-Rounder Star",
    category: "Overall Excellence",
    description: "Best overall performer across all training categories.",
    winners: [
      {
        candidateId: "AGN-2024-0404",
        candidateName: "Vijay Deshmukh",
        battalion: "MAR-4",
        awardedOn: "2024-12-31",
        awardedBy: "Brig. Training",
        citation: "Highest aggregate score across all training parameters.",
        relatedEventId: "best-all-rounder-2024",
      },
    ],
  },
  {
    id: "para-jump-certificate",
    title: "Para Jump Certification",
    category: "Special Operations",
    description: "Certification for successful completion of para jumping training.",
    winners: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        awardedOn: "2024-03-15",
        awardedBy: "Chief Instructor, PTS",
        citation: "Successfully completed all 5 para jumps.",
        relatedEventId: "para-jump-certification-2024",
      },
      {
        candidateId: "AGN-2024-0204",
        candidateName: "Deepak Yadav",
        battalion: "PARA-2",
        awardedOn: "2024-03-15",
        awardedBy: "Chief Instructor, PTS",
        citation: "Successfully completed all 5 para jumps.",
        relatedEventId: "para-jump-certification-2024",
      },
    ],
  },
  {
    id: "best-para-recruit-award",
    title: "Best Para Recruit",
    category: "Special Operations",
    description: "Best performing recruit in para training.",
    winners: [
      {
        candidateId: "AGN-2024-0201",
        candidateName: "Vikram Nair",
        battalion: "PARA-2",
        awardedOn: "2024-04-01",
        awardedBy: "Commandant, PTS",
        citation: "Highest aggregate in para recruit training.",
        relatedEventId: "best-para-recruit-2024",
      },
    ],
  },
  {
    id: "battalion-champion-award",
    title: "Battalion Physical Champion",
    category: "Physical Excellence",
    description: "Best physical performer in battalion championship.",
    winners: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        awardedOn: "2024-10-05",
        awardedBy: "Battalion Commander",
        citation: "Highest aggregate in physical parameters.",
        relatedEventId: "battalion-physical-champion-2024",
      },
    ],
  },
  {
    id: "all-india-rank-award",
    title: "All India Rank Award",
    category: "National Recognition",
    description: "Recognition for top national ranking.",
    winners: [
      {
        candidateId: "AGN-2024-0103",
        candidateName: "Arjun Mehra",
        battalion: "RR-1",
        awardedOn: "2025-03-15",
        awardedBy: "DG, Agniveer Scheme",
        citation: "All India Rank #1 in Agniveer performance.",
        relatedEventId: "all-india-ranking-2025",
      },
    ],
  },
]
