export const PLATOONS = [
  {
    id: "PL-001",
    name: "Platoon 1",
    company: "Lakhwinder",
    totalSoldiers: 38,
    commander: "Maj. Vikram Rathore",
    avgPhysical: 86.2,
    avgWeapons: 80.4,
    avgCombat: 84.0,
    avgTactics: 79.1,
    overall: 82.4,
    color: "#25447C",
  },
  {
    id: "PL-002",
    name: "Platoon 2",
    company: "Jaswant",
    totalSoldiers: 35,
    commander: "Capt. Suresh Negi",
    avgPhysical: 81.9,
    avgWeapons: 78.1,
    avgCombat: 80.4,
    avgTactics: 81.3,
    overall: 80.4,
    color: "#4A5C2F",
  },
  {
    id: "PL-003",
    name: "Platoon 3",
    company: "Arora",
    totalSoldiers: 33,
    commander: "Capt. Rajeev Sharma",
    avgPhysical: 87.7,
    avgWeapons: 82.6,
    avgCombat: 85.7,
    avgTactics: 82.2,
    overall: 84.5,
    color: "#2767A0",
  },
  {
    id: "PL-004",
    name: "Platoon 4",
    company: "Thorat",
    totalSoldiers: 29,
    commander: "Lt. Amit Singh",
    avgPhysical: 73.2,
    avgWeapons: 77.9,
    avgCombat: 73.4,
    avgTactics: 73.8,
    overall: 74.6,
    color: "#775222",
  },
  {
    id: "PL-005",
    name: "Platoon 5",
    company: "Mahadev",
    totalSoldiers: 30,
    commander: "Lt. Rohit Shekhawat",
    avgPhysical: 79.9,
    avgWeapons: 76.8,
    avgCombat: 79.1,
    avgTactics: 78.6,
    overall: 78.6,
    color: "#4A5C2F",
  },
]
